/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ExpertSection(props) {
	const group = useRef()
	const { nodes, materials, animations } = useGLTF('./models/iconography/INCONOGRAPHY_Expert_v13.glb')
	const { actions } = useAnimations(animations, group)

	useEffect(() => {
		// actions['BOLT.001Action.001'].play()
		// actions['BULB_BOLTAction'].play()
		// actions['POWER BAR.001Action.001'].play()
		// actions['POWER BAR.002Action.001'].play()
		// actions['POWER BAR.003Action.001'].play()
		// actions['bulbAction'].play()
		// actions['poundAction.001'].play()
		// actions['powerStationAction.002'].play()
	}, [])

	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Scene'>
				<group name='poundSymbol'>
					<mesh name='POUND_SYMBOL' castShadow receiveShadow geometry={nodes.POUND_SYMBOL.geometry} material={materials['Hireco-whiteMetal-poundSymbol-1']} position={[-0.01, -0.07, 0]} />
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('./models/iconography/INCONOGRAPHY_Expert_v13.glb')
