/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import { LoopOnce } from 'three'

export function VanModel(props) {
	const { index } = props
	const group = useRef()
	const { nodes, materials, animations } = useGLTF('./models/iconography/INCONOGRAPHY_source_van_v1.glb')
	const { actions } = useAnimations(animations, group)
	// console.log(actions)

	useEffect(() => {
		// actions.Action.play()
		// actions.vanActions.setDuration(1)
		// actions.vanAction.startAt(20)
		// actions.vanAction.setDuration(10)
		actions.vanAction.setDuration(5).play()
		// actions.vanWheel_1Action.play()
		// actions.vanWheel_2Action.play()
		// actions.vanWheel_3Action.play()
		// actions.vanWheel_4Action.play()
	}, [])

	return (
		<group ref={group} {...props} dispose={null} scale={0.06}>
			<group name='Scene'>
				<group name='van'>
					<mesh name='van_1' geometry={nodes.van_1.geometry} material={materials['H ORANGE.001']} position={[0, 0, 0.19]}>
						<mesh name='van_windows_1' geometry={nodes.van_windows_1.geometry} material={materials.tintedWindow} />
					</mesh>
					<mesh name='vanWheel_1' geometry={nodes.vanWheel_1.geometry} material={materials['H ORANGE.001']} position={[-0.3, -0.11, 0.15]} />
					<mesh name='vanWheel_2' geometry={nodes.vanWheel_2.geometry} material={materials['H ORANGE.001']} position={[0.38, -0.11, 0.15]} />
					<mesh name='vanWheel_3' geometry={nodes.vanWheel_3.geometry} material={materials['H ORANGE.001']} position={[-0.3, -0.11, -0.15]} />
					<mesh name='vanWheel_4' geometry={nodes.vanWheel_4.geometry} material={materials['H ORANGE.001']} position={[0.38, -0.11, -0.15]} />
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('./models/iconography/INCONOGRAPHY_source_van_v1.glb')
