/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tl0615 (https://sketchfab.com/tl0615)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/new-rose-hotel-0653d651ed5c408cbeb5f3e028dd28e1
title: New Rose Hotel
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
	const { nodes, materials } = useGLTF('./new_rose_hotel.glb')
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={28.57}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group position={[-0.31, 0, 0.89]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.42, 16.31, 0.42]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.material_0} />
					</group>
					<group position={[-0.49, 0.25, 0.23]} rotation={[-Math.PI / 2, 0, -0.89]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.49, 0.25, 0.23]} rotation={[-Math.PI / 2, 0, -0.89]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.49, 0.25, 0.23]} rotation={[-Math.PI / 2, 0, -0.89]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.49, 0.25, 0.23]} rotation={[-Math.PI / 2, 0, -0.89]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.49, 0.25, 0.23]} rotation={[-Math.PI / 2, 0, -0.89]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.49, 0.25, 0.23]} rotation={[-Math.PI / 2, 0, -0.89]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.56, 0.25, 0.13]} rotation={[-Math.PI / 2, 0, -1.26]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.56, 0.25, 0.13]} rotation={[-Math.PI / 2, 0, -1.26]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.56, 0.25, 0.13]} rotation={[-Math.PI / 2, 0, -1.26]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.56, 0.25, 0.13]} rotation={[-Math.PI / 2, 0, -1.26]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.56, 0.25, 0.13]} rotation={[-Math.PI / 2, 0, -1.26]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials.material_1} />
					</group>
					<group position={[-0.56, 0.25, 0.13]} rotation={[-Math.PI / 2, 0, -1.26]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials.material_1} />
					</group>
					<group position={[0.07, 0.25, 0.57]} rotation={[-Math.PI / 2, 0, 0]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_30.geometry} material={materials.material_2} />
					</group>
					<group position={[0.07, 0.25, 0.57]} rotation={[-Math.PI / 2, 0, 0]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_32.geometry} material={materials.material_2} />
					</group>
					<group position={[0.07, 0.25, 0.57]} rotation={[-Math.PI / 2, 0, 0]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials.material_2} />
					</group>
					<group position={[0.07, 0.25, 0.57]} rotation={[-Math.PI / 2, 0, 0]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_36.geometry} material={materials.material_2} />
					</group>
					<group position={[0.07, 0.25, 0.57]} rotation={[-Math.PI / 2, 0, 0]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_38.geometry} material={materials.material_2} />
					</group>
					<group position={[-0.19, 0.25, 0.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.49, 0.87, 0.15]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_40.geometry} material={materials.material_3} />
					</group>
					<group position={[-0.19, 0.25, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.13, 0.26, 0.16]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_42.geometry} material={materials.material_3} />
					</group>
					<group position={[-0.18, 0.33, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.03, 0.27, 0.16]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_44.geometry} material={materials.material_3} />
					</group>
					<group position={[0.06, 0.02, 0.74]} rotation={[-Math.PI / 2, 0, 0]} scale={1.24}>
						<mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials.material_21} />
						<mesh castShadow receiveShadow geometry={nodes.Object_46.geometry} material={materials.material_4} />
					</group>
					<group position={[0.05, 0.11, 0.72]} rotation={[-Math.PI / 2, -0.43, 0]} scale={1.24}>
						<mesh castShadow receiveShadow geometry={nodes.Object_50.geometry} material={materials.material_21} />
						<mesh castShadow receiveShadow geometry={nodes.Object_49.geometry} material={materials.material_4} />
					</group>
					<group position={[0.05, 0.02, 0.73]} rotation={[-Math.PI / 2, 0, 0]} scale={1.24}>
						<mesh castShadow receiveShadow geometry={nodes.Object_53.geometry} material={materials.material_21} />
						<mesh castShadow receiveShadow geometry={nodes.Object_52.geometry} material={materials.material_4} />
					</group>
					<group position={[-0.68, 0.02, 0.33]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_55.geometry} material={materials.material_5} />
					</group>
					<group position={[-0.08, 0.07, -0.13]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_57.geometry} material={materials.material_6} />
					</group>
					<group position={[-0.1, 0.04, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_59.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.1, 0.12, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 7.28]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_61.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.08, 0.14, -0.09]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_63.geometry} material={materials.material_6} />
					</group>
					<group position={[-0.02, 0.07, -0.13]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_65.geometry} material={materials.material_6} />
					</group>
					<group position={[-0.03, 0.04, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_67.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.03, 0.12, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 7.28]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_69.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.02, 0.14, -0.09]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_71.geometry} material={materials.material_6} />
					</group>
					<group position={[0.05, 0.07, -0.13]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_73.geometry} material={materials.material_6} />
					</group>
					<group position={[0.03, 0.04, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_75.geometry} material={materials.material_7} />
					</group>
					<group position={[0.03, 0.12, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 7.28]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_77.geometry} material={materials.material_7} />
					</group>
					<group position={[0.05, 0.14, -0.09]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_79.geometry} material={materials.material_6} />
					</group>
					<group position={[0.11, 0.07, -0.13]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_81.geometry} material={materials.material_6} />
					</group>
					<group position={[0.09, 0.04, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_83.geometry} material={materials.material_7} />
					</group>
					<group position={[0.09, 0.12, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 7.27]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_85.geometry} material={materials.material_7} />
					</group>
					<group position={[0.11, 0.14, -0.09]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_87.geometry} material={materials.material_6} />
					</group>
					<group position={[0.17, 0.07, -0.13]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_89.geometry} material={materials.material_6} />
					</group>
					<group position={[0.15, 0.04, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_91.geometry} material={materials.material_7} />
					</group>
					<group position={[0.15, 0.12, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 7.28]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_93.geometry} material={materials.material_7} />
					</group>
					<group position={[0.17, 0.14, -0.09]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_95.geometry} material={materials.material_6} />
					</group>
					<group position={[0.2, 0.1, -0.17]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[2.05, 0.25, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_97.geometry} material={materials.material_8} />
					</group>
					<group position={[-0.1, 0.19, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_99.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.08, 0.21, -0.03]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_101.geometry} material={materials.material_6} />
					</group>
					<group position={[-0.03, 0.19, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_103.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.02, 0.21, -0.03]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_105.geometry} material={materials.material_6} />
					</group>
					<group position={[0.03, 0.19, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_107.geometry} material={materials.material_7} />
					</group>
					<group position={[0.05, 0.21, -0.03]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_109.geometry} material={materials.material_6} />
					</group>
					<group position={[0.09, 0.19, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_111.geometry} material={materials.material_7} />
					</group>
					<group position={[0.11, 0.21, -0.03]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_113.geometry} material={materials.material_6} />
					</group>
					<group position={[0.15, 0.19, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_115.geometry} material={materials.material_7} />
					</group>
					<group position={[0.17, 0.21, -0.03]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_117.geometry} material={materials.material_6} />
					</group>
					<group position={[0.2, 0.17, -0.11]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[1.85, 0.25, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_119.geometry} material={materials.material_8} />
					</group>
					<group position={[-0.09, 0.02, 0.18]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_121.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.03, 0.02, 0.18]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_123.geometry} material={materials.material_7} />
					</group>
					<group position={[0.03, 0.02, 0.18]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_125.geometry} material={materials.material_7} />
					</group>
					<group position={[0.1, 0.02, 0.18]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_127.geometry} material={materials.material_7} />
					</group>
					<group position={[0.16, 0.02, 0.18]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_129.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.14, 0.1, -0.13]} rotation={[-0.52, -0.02, 3.13]} scale={[0.26, 0.71, 0.69]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_131.geometry} material={materials.material_8} />
					</group>
					<group position={[-0.14, 0.17, -0.11]} rotation={[-2.67, 0.01, -0.01]} scale={[0.25, 0.65, 0.65]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_133.geometry} material={materials.material_8} />
					</group>
					<group position={[0.16, 0.17, -0.04]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_135.geometry} material={materials.material_9} />
					</group>
					<group position={[0.1, 0.17, -0.04]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_137.geometry} material={materials.material_9} />
					</group>
					<group position={[0.04, 0.17, -0.04]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_139.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.02, 0.17, -0.05]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_141.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.08, 0.17, -0.05]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_143.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.08, 0.09, -0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_145.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.02, 0.09, -0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_147.geometry} material={materials.material_9} />
					</group>
					<group position={[0.04, 0.09, -0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_149.geometry} material={materials.material_9} />
					</group>
					<group position={[0.1, 0.09, -0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_151.geometry} material={materials.material_9} />
					</group>
					<group position={[0.16, 0.09, -0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_153.geometry} material={materials.material_9} />
					</group>
					<group position={[0.16, 0.02, -0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_155.geometry} material={materials.material_9} />
					</group>
					<group position={[0.1, 0.02, -0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_157.geometry} material={materials.material_9} />
					</group>
					<group position={[0.04, 0.02, -0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_159.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.02, 0.02, -0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_161.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.08, 0.02, -0.08]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 0.05]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_163.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.08, 0.02, -0.18]} rotation={[Math.PI, 0, 0]} scale={[0.53, 0.57, 0.03]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_165.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.1, 0.05, 0.01]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 2.2, 0.15]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_167.geometry} material={materials.material_10} />
					</group>
					<group position={[-0.12, 0.07, -0.11]} rotation={[-0.79, -0.01, -0.01]} scale={[0.39, 0.27, 0.34]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_169.geometry} material={materials.material_11} />
					</group>
					<group position={[0.22, 0.02, -0.2]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[2.21, 1.98, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_171.geometry} material={materials.material_8} />
					</group>
					<group position={[0.19, 0.02, -0.2]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[2.05, 0.25, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_173.geometry} material={materials.material_12} />
					</group>
					<group position={[-0.08, 0.3, 0.01]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_175.geometry} material={materials.material_6} />
					</group>
					<group position={[-0.1, 0.27, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_177.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.1, 0.35, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 6.85]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_179.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.08, 0.37, 0.06]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_181.geometry} material={materials.material_6} />
					</group>
					<group position={[-0.02, 0.3, 0.01]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_183.geometry} material={materials.material_6} />
					</group>
					<group position={[-0.03, 0.27, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_185.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.03, 0.35, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 6.85]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_187.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.02, 0.37, 0.06]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_189.geometry} material={materials.material_6} />
					</group>
					<group position={[0.05, 0.3, 0.01]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_191.geometry} material={materials.material_6} />
					</group>
					<group position={[0.03, 0.27, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_193.geometry} material={materials.material_7} />
					</group>
					<group position={[0.03, 0.35, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 6.85]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_195.geometry} material={materials.material_7} />
					</group>
					<group position={[0.05, 0.37, 0.06]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_197.geometry} material={materials.material_6} />
					</group>
					<group position={[0.11, 0.3, 0.01]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_199.geometry} material={materials.material_6} />
					</group>
					<group position={[0.09, 0.27, 0.15]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_201.geometry} material={materials.material_7} />
					</group>
					<group position={[0.09, 0.34, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 6.83]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_203.geometry} material={materials.material_7} />
					</group>
					<group position={[0.11, 0.37, 0.06]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_205.geometry} material={materials.material_6} />
					</group>
					<group position={[0.17, 0.3, 0.01]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_207.geometry} material={materials.material_6} />
					</group>
					<group position={[0.15, 0.27, 0.15]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 8.96]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_209.geometry} material={materials.material_7} />
					</group>
					<group position={[0.15, 0.35, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 6.85]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_211.geometry} material={materials.material_7} />
					</group>
					<group position={[0.17, 0.37, 0.06]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_213.geometry} material={materials.material_6} />
					</group>
					<group position={[0.2, 0.32, -0.03]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[2.02, 0.29, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_215.geometry} material={materials.material_8} />
					</group>
					<group position={[-0.1, 0.42, 0.14]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_217.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.08, 0.44, 0.11]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_219.geometry} material={materials.material_6} />
					</group>
					<group position={[-0.03, 0.42, 0.15]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_221.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.02, 0.44, 0.11]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_223.geometry} material={materials.material_6} />
					</group>
					<group position={[0.03, 0.42, 0.15]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_225.geometry} material={materials.material_7} />
					</group>
					<group position={[0.05, 0.44, 0.11]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_227.geometry} material={materials.material_6} />
					</group>
					<group position={[0.09, 0.42, 0.15]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_229.geometry} material={materials.material_7} />
					</group>
					<group position={[0.11, 0.44, 0.11]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_231.geometry} material={materials.material_6} />
					</group>
					<group position={[0.15, 0.42, 0.15]} rotation={[-Math.PI, 0.01, 0]} scale={[0.2, 0.14, 4.5]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_233.geometry} material={materials.material_7} />
					</group>
					<group position={[0.17, 0.44, 0.11]} rotation={[-Math.PI, 0.01, 0]} scale={[0.88, 0.88, 4.99]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_235.geometry} material={materials.material_6} />
					</group>
					<group position={[0.2, 0.4, 0.03]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[1.85, 0.25, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_237.geometry} material={materials.material_8} />
					</group>
					<group position={[-0.09, 0.25, 0.32]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_239.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.03, 0.25, 0.32]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_241.geometry} material={materials.material_7} />
					</group>
					<group position={[0.03, 0.25, 0.32]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_243.geometry} material={materials.material_7} />
					</group>
					<group position={[0.1, 0.25, 0.32]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_245.geometry} material={materials.material_7} />
					</group>
					<group position={[0.16, 0.25, 0.32]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 1.1, 8.29]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_247.geometry} material={materials.material_7} />
					</group>
					<group position={[-0.14, 0.33, 0.01]} rotation={[-0.52, 0.01, -3.13]} scale={[0.26, 0.71, 0.83]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_249.geometry} material={materials.material_8} />
					</group>
					<group position={[-0.14, 0.4, 0.03]} rotation={[-2.67, 0.01, -0.01]} scale={[0.25, 0.65, 0.37]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_251.geometry} material={materials.material_8} />
					</group>
					<group position={[0.16, 0.39, 0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_253.geometry} material={materials.material_9} />
					</group>
					<group position={[0.1, 0.39, 0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_255.geometry} material={materials.material_9} />
					</group>
					<group position={[0.04, 0.39, 0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_257.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.02, 0.39, 0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_259.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.08, 0.39, 0.1]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_261.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.08, 0.32, 0.05]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_263.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.02, 0.32, 0.05]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_265.geometry} material={materials.material_9} />
					</group>
					<group position={[0.04, 0.32, 0.05]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_267.geometry} material={materials.material_9} />
					</group>
					<group position={[0.1, 0.32, 0.05]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_269.geometry} material={materials.material_9} />
					</group>
					<group position={[0.16, 0.32, 0.05]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_271.geometry} material={materials.material_9} />
					</group>
					<group position={[0.16, 0.25, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_273.geometry} material={materials.material_9} />
					</group>
					<group position={[0.1, 0.25, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_275.geometry} material={materials.material_9} />
					</group>
					<group position={[0.04, 0.25, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_277.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.02, 0.25, 0]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 1.33]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_279.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.08, 0.25, 0.06]} rotation={[-Math.PI, 0.01, 0]} scale={[0.53, 0.57, 0.05]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_281.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.07, 0.25, -0.06]} rotation={[Math.PI, 1.09, 0]} scale={[0.53, 0.57, 0.03]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_283.geometry} material={materials.material_9} />
					</group>
					<group position={[-0.1, 0.28, 0.15]} rotation={[-Math.PI / 2, 0, -0.01]} scale={[1, 2.2, 0.15]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_285.geometry} material={materials.material_13} />
					</group>
					<group position={[-0.12, 0.29, 0.02]} rotation={[-0.79, -0.01, -0.01]} scale={[0.39, 0.27, 0.34]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_287.geometry} material={materials.material_11} />
					</group>
					<group position={[0.2, 0.24, -0.06]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[2.12, 1.15, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_289.geometry} material={materials.material_8} />
					</group>
					<group position={[0.19, 0.25, -0.06]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[2.05, 0.25, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_291.geometry} material={materials.material_12} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_293.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_295.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_297.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_299.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_301.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_303.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_305.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_307.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_309.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_311.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_313.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_315.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_317.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_319.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_321.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_323.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_325.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_327.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_329.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_331.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_333.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_335.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_337.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_339.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_341.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_343.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_345.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_347.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_349.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_351.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_353.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_355.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_357.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_359.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_361.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_363.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_365.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_367.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_369.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_371.geometry} material={materials.material_14} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_373.geometry} material={materials.material_7} />
					</group>
					<group position={[0.2, 0.02, 0.14]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.12, 2.13, 12.25]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_375.geometry} material={materials.material_14} />
					</group>
					<group position={[0.22, 0.02, 0.08]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[2.25, 0.42, 1.05]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_377.geometry} material={materials.material_8} />
					</group>
					<group position={[-0.14, 0.25, -0.06]} rotation={[-2.67, 0.01, -0.01]} scale={[0.25, 0.64, 0.74]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_379.geometry} material={materials.material_8} />
					</group>
					<group position={[0.19, 0.02, -0.08]} rotation={[-Math.PI / 2, 0, 3.13]} scale={[2.05, 0.25, 0.22]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_381.geometry} material={materials.material_8} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_383.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_385.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_387.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_389.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_391.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_393.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_395.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_397.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_399.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_401.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_403.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_405.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_407.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_409.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_411.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_413.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_415.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_417.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_419.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_421.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_423.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_425.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_427.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_429.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_431.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_433.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_435.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_437.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_439.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_441.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_443.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_445.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_447.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_449.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_451.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.09, 0.31, 0.04]} rotation={[-1.57, -1.54, -1.57]} scale={1.29}>
						<mesh castShadow receiveShadow geometry={nodes.Object_453.geometry} material={materials.material_15} />
					</group>
					<group position={[-0.14, 0.17, -0.07]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.85, 0.25, 0.16]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_455.geometry} material={materials.material_3} />
					</group>
					<group position={[-0.18, 0.1, -0.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.07, 0.27, 0.16]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_457.geometry} material={materials.material_3} />
					</group>
					<group position={[-0.19, 0.02, -0.16]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.2, 0.29, 0.4]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_459.geometry} material={materials.material_3} />
					</group>
					<group position={[-0.14, 0.4, 0.07]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.87, 0.24, 0.16]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_461.geometry} material={materials.material_3} />
					</group>
					<group position={[-0.7, 0.21, -0.22]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.03, 0.04, 0.03]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_463.geometry} material={materials.material_16} />
					</group>
					<group position={[-0.7, 0.21, -0.22]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.03, 0.04, 0.03]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_468.geometry} material={materials.material_21} />
						<mesh castShadow receiveShadow geometry={nodes.Object_465.geometry} material={materials.material_17} />
						<mesh castShadow receiveShadow geometry={nodes.Object_466.geometry} material={materials.material_18} />
						<mesh castShadow receiveShadow geometry={nodes.Object_467.geometry} material={materials.material_19} />
					</group>
					<group position={[-0.42, 0.23, -0.54]} rotation={[-1.57, 0, -2.27]} scale={[0.03, 0.04, 0.03]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_470.geometry} material={materials.material_16} />
					</group>
					<group position={[-0.42, 0.23, -0.54]} rotation={[-1.57, 0, -2.27]} scale={[0.03, 0.04, 0.03]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_475.geometry} material={materials.material_21} />
						<mesh castShadow receiveShadow geometry={nodes.Object_472.geometry} material={materials.material_17} />
						<mesh castShadow receiveShadow geometry={nodes.Object_473.geometry} material={materials.material_18} />
						<mesh castShadow receiveShadow geometry={nodes.Object_474.geometry} material={materials.material_19} />
					</group>
					<group position={[-0.43, 0.23, -0.54]} rotation={[-1.57, 0, -2.27]} scale={[0.03, 0.04, 0.03]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_477.geometry} material={materials.material_16} />
					</group>
					<group position={[-0.43, 0.23, -0.54]} rotation={[-1.57, 0, -2.27]} scale={[0.03, 0.04, 0.03]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_482.geometry} material={materials.material_21} />
						<mesh castShadow receiveShadow geometry={nodes.Object_479.geometry} material={materials.material_17} />
						<mesh castShadow receiveShadow geometry={nodes.Object_480.geometry} material={materials.material_18} />
						<mesh castShadow receiveShadow geometry={nodes.Object_481.geometry} material={materials.material_19} />
					</group>
					<group position={[-0.19, 0.15, -0.07]} rotation={[0, -1.57, 0]} scale={[1.62, 1.04, 0.37]}>
						<mesh castShadow receiveShadow geometry={nodes.Object_484.geometry} material={materials.material_20} />
					</group>
				</group>
			</group>
		</group>
	)
}

function ModelComponent_old(props) {
	// This reference will give us direct access to the mesh
	const mesh = useRef()
	// Set up state for the hovered and active state
	const [hovered, setHover] = useState(false)
	const [active, setActive] = useState(false)
	// Subscribe this component to the render-loop, rotate the mesh every frame
	useFrame((state, delta) => (mesh.current.rotation.y += delta))
	// Return view, these are regular three.js elements expressed in JSX
	return (
		<mesh {...props} ref={mesh} scale={0.25}>
			{/* <boxGeometry args={[1, 1, 1]} /> */}
			<Model />
			{/* <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'} /> */}
		</mesh>
	)
}

function ModelComponent(props) {
	// This reference will give us direct access to the mesh
	const mesh = useRef()
	// Set up state for the hovered and active state
	const [hovered, setHover] = useState(false)
	const [active, setActive] = useState(false)
	// Subscribe this component to the render-loop, rotate the mesh every frame
	useFrame((state, delta) => (mesh.current.rotation.y += delta))
	// Return view, these are regular three.js elements expressed in JSX
	return (
		<mesh {...props} ref={mesh} scale={0.25}>
			{/* <boxGeometry args={[1, 1, 1]} /> */}
			<Model />
			{/* <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'} /> */}
		</mesh>
	)
}

useGLTF.preload('./new_rose_hotel.glb')
