/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function WelfareSection(props) {
	const group = useRef()
	const { nodes, materials, animations } = useGLTF('./models/iconography/INCONOGRAPHY_welfare_v1.glb')
	const { actions } = useAnimations(animations, group)

	useEffect(() => {
		actions['PAction.001'].play()
		actions['heartAction.002'].play()
		actions['knifeAndForkAction'].play()
		actions['knifeAndFork_knifeAction'].play()
	}, [])

	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Scene'>
				<group name='knifeAndFork'>
					<mesh name='knifeAndFork_fork' castShadow receiveShadow geometry={nodes.knifeAndFork_fork.geometry} material={materials.orangeSolid} position={[-0.16, -0.22, 0]} rotation={[Math.PI / 2, -Math.PI / 4, 0]} scale={[0.02, 0.02, 0.22]} />
					<mesh name='knifeAndFork_knife' castShadow receiveShadow geometry={nodes.knifeAndFork_knife.geometry} material={materials.orangeSolid} position={[0.19, -0.31, -0.02]} rotation={[Math.PI / 2, Math.PI / 4, 0]} scale={0.03} />
				</group>
				<group name='P001' scale={0}>
					<mesh name='P' castShadow receiveShadow geometry={nodes.P.geometry} material={materials.orangeSolid} position={[0.06, 0.02, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.55} />
				</group>
				<group name='heart' scale={0}>
					<mesh name='heart_1' castShadow receiveShadow geometry={nodes.heart_1.geometry} material={materials.orangeSolid} rotation={[Math.PI / 2, 0, 0]} scale={9.37} />
				</group>
				<mesh name='invisibleSphere' castShadow receiveShadow geometry={nodes.invisibleSphere.geometry} material={materials.invisible} scale={0.6} />
			</group>
		</group>
	)
}

useGLTF.preload('./models/iconography/INCONOGRAPHY_welfare_v1.glb')
